export type ActionScope = 'local' | 'server' | 'hybrid';

export interface ActionMeta {
    action: string;
    scope: ActionScope;
    domain: string;
    description?: string;
}

export const ACTION_CATALOG: readonly ActionMeta[] = [
    { action: 'read', scope: 'hybrid', domain: 'crud' },
    { action: 'get', scope: 'hybrid', domain: 'crud' },
    { action: 'list', scope: 'hybrid', domain: 'crud' },
    { action: 'query', scope: 'hybrid', domain: 'crud' },
    { action: 'create', scope: 'hybrid', domain: 'crud' },
    { action: 'update', scope: 'hybrid', domain: 'crud' },
    { action: 'delete', scope: 'hybrid', domain: 'crud' },
    { action: 'auth_login', scope: 'server', domain: 'auth' },
    { action: 'auth_refresh_session', scope: 'server', domain: 'auth' },
    { action: 'auth_resolve_tenant', scope: 'server', domain: 'auth' },
    { action: 'auth_me', scope: 'server', domain: 'auth' },
    { action: 'get_current_user', scope: 'server', domain: 'auth' },
    { action: 'auth_logout', scope: 'server', domain: 'auth' },
    { action: 'public_register', scope: 'server', domain: 'auth' },
    { action: 'list_themes', scope: 'local', domain: 'theme' },
    { action: 'activate_theme', scope: 'local', domain: 'theme' },
    { action: 'get_active_theme_home', scope: 'local', domain: 'theme' },
    { action: 'get_active_theme_id', scope: 'local', domain: 'theme' },
    { action: 'save_theme_part', scope: 'local', domain: 'theme' },
    { action: 'load_theme_part', scope: 'local', domain: 'theme' },
    { action: 'update_theme_colors', scope: 'local', domain: 'theme' },
    { action: 'list_products', scope: 'hybrid', domain: 'store' },
    { action: 'read_product', scope: 'hybrid', domain: 'store' },
    { action: 'create_product', scope: 'local', domain: 'store' },
    { action: 'update_product', scope: 'local', domain: 'store' },
    { action: 'delete_product', scope: 'local', domain: 'store' },
    { action: 'query_products', scope: 'hybrid', domain: 'store' },
    { action: 'update_stock', scope: 'hybrid', domain: 'store' },
    { action: 'list_inventory_logs', scope: 'local', domain: 'store' },
    { action: 'list_payment_methods', scope: 'hybrid', domain: 'store' },
    { action: 'update_payment_method', scope: 'local', domain: 'store' },
    { action: 'list_coupons', scope: 'local', domain: 'store' },
    { action: 'create_coupon', scope: 'local', domain: 'store' },
    { action: 'update_coupon', scope: 'local', domain: 'store' },
    { action: 'delete_coupon', scope: 'local', domain: 'store' },
    { action: 'validate_coupon', scope: 'hybrid', domain: 'store' },
    { action: 'list_orders', scope: 'hybrid', domain: 'store' },
    { action: 'update_order_status', scope: 'hybrid', domain: 'store' },
    { action: 'create_sale', scope: 'hybrid', domain: 'store' },
    { action: 'get_company_settings', scope: 'hybrid', domain: 'store' },
    { action: 'update_company_settings', scope: 'local', domain: 'store' },
    { action: 'get_legal_settings', scope: 'hybrid', domain: 'store' },
    { action: 'update_legal_settings', scope: 'local', domain: 'store' },
    { action: 'get_payment_settings', scope: 'hybrid', domain: 'store' },
    { action: 'update_payment_settings', scope: 'local', domain: 'store' },
    { action: 'create_payment_intent', scope: 'server', domain: 'payments' },
    { action: 'revolut_webhook', scope: 'server', domain: 'payments' },
    { action: 'create_revolut_payment', scope: 'server', domain: 'payments' },
    { action: 'check_revolut_payment', scope: 'server', domain: 'payments' },
    { action: 'get_table_order', scope: 'server', domain: 'qr' },
    { action: 'process_external_order', scope: 'server', domain: 'qr' },
    { action: 'update_table_cart', scope: 'server', domain: 'qr' },
    { action: 'clear_table', scope: 'server', domain: 'qr' },
    { action: 'table_request', scope: 'server', domain: 'qr' },
    { action: 'get_table_requests', scope: 'server', domain: 'qr' },
    { action: 'acknowledge_request', scope: 'server', domain: 'qr' },
    { action: 'generate_qr_list', scope: 'local', domain: 'qr' },
    { action: 'get_mesa_settings', scope: 'hybrid', domain: 'qr' },
    { action: 'list_reservas', scope: 'hybrid', domain: 'reservas' },
    { action: 'create_reserva', scope: 'server', domain: 'reservas' },
    { action: 'get_availability', scope: 'hybrid', domain: 'reservas' },
    { action: 'list_courses', scope: 'hybrid', domain: 'academy' },
    { action: 'create_course', scope: 'local', domain: 'academy' },
    { action: 'create_lesson', scope: 'local', domain: 'academy' },
    { action: 'update_course', scope: 'local', domain: 'academy' },
    { action: 'delete_course', scope: 'local', domain: 'academy' },
    { action: 'chat', scope: 'server', domain: 'ai' },
    { action: 'ask', scope: 'server', domain: 'ai' },
    { action: 'chat_restaurant', scope: 'server', domain: 'ai' },
    { action: 'load_conversation', scope: 'local', domain: 'ai' },
    { action: 'save_conversation', scope: 'local', domain: 'ai' },
    { action: 'list_conversations', scope: 'local', domain: 'ai' },
    { action: 'list_models', scope: 'server', domain: 'ai' },
    { action: 'upload_carta_source', scope: 'server', domain: 'carta' },
    { action: 'ocr_extract', scope: 'server', domain: 'carta' },
    { action: 'ocr_parse', scope: 'server', domain: 'carta' },
    { action: 'enhance_image_sync', scope: 'server', domain: 'carta' },
    { action: 'ai_sugerir_alergenos', scope: 'server', domain: 'carta' },
    { action: 'ai_generar_descripcion', scope: 'server', domain: 'carta' },
    { action: 'ai_generar_promocion', scope: 'server', domain: 'carta' },
    { action: 'ai_traducir', scope: 'server', domain: 'carta' },
    { action: 'importar_carta_estructurada', scope: 'server', domain: 'carta' },
    { action: 'generate_pdf_carta', scope: 'server', domain: 'carta' },
    { action: 'sala_resumen', scope: 'server', domain: 'sala' },
    { action: 'list_zonas', scope: 'server', domain: 'sala' },
    { action: 'create_zona', scope: 'server', domain: 'sala' },
    { action: 'update_zona', scope: 'server', domain: 'sala' },
    { action: 'delete_zona', scope: 'server', domain: 'sala' },
    { action: 'create_zonas_preset', scope: 'server', domain: 'sala' },
    { action: 'reorder_zonas', scope: 'server', domain: 'sala' },
    { action: 'list_mesas', scope: 'server', domain: 'sala' },
    { action: 'create_mesa', scope: 'server', domain: 'sala' },
    { action: 'update_mesa', scope: 'server', domain: 'sala' },
    { action: 'delete_mesa', scope: 'server', domain: 'sala' },
    { action: 'create_mesas_batch', scope: 'server', domain: 'sala' },
    { action: 'regenerate_mesa_qr', scope: 'server', domain: 'sala' },
    { action: 'get_local', scope: 'server', domain: 'local' },
    { action: 'list_my_locales', scope: 'server', domain: 'local' },
    { action: 'create_local', scope: 'server', domain: 'local' },
    { action: 'update_local', scope: 'server', domain: 'local' },
    { action: 'bootstrap_local', scope: 'server', domain: 'local' },
    { action: 'upload_local_image', scope: 'server', domain: 'local' },
    { action: 'list_cartas', scope: 'server', domain: 'carta' },
    { action: 'create_carta', scope: 'server', domain: 'carta' },
    { action: 'update_carta', scope: 'server', domain: 'carta' },
    { action: 'delete_carta', scope: 'server', domain: 'carta' },
    { action: 'list_categorias', scope: 'server', domain: 'carta' },
    { action: 'create_categoria', scope: 'server', domain: 'carta' },
    { action: 'update_categoria', scope: 'server', domain: 'carta' },
    { action: 'delete_categoria', scope: 'server', domain: 'carta' },
    { action: 'list_productos', scope: 'server', domain: 'carta' },
    { action: 'create_producto', scope: 'server', domain: 'carta' },
    { action: 'update_producto', scope: 'server', domain: 'carta' },
    { action: 'delete_producto', scope: 'server', domain: 'carta' },
    { action: 'create_subscription', scope: 'server', domain: 'billing' },
    { action: 'activate_subscription', scope: 'server', domain: 'billing' },
    { action: 'cancel_subscription', scope: 'server', domain: 'billing' },
    { action: 'get_subscription', scope: 'server', domain: 'billing' },
    { action: 'health_check', scope: 'local', domain: 'system' },
    { action: 'build_site', scope: 'server', domain: 'system' },
    { action: 'generate_sitemap', scope: 'server', domain: 'system' },
    { action: 'upload', scope: 'server', domain: 'system' },
    { action: 'synaxis_sync', scope: 'server', domain: 'system' },
    { action: 'list_glands', scope: 'local', domain: 'system' },
    { action: 'get_marketplace', scope: 'hybrid', domain: 'system' },
    // CITAS
    { action: 'cita_create', scope: 'server', domain: 'citas' },
    { action: 'cita_list', scope: 'server', domain: 'citas' },
    { action: 'cita_cancel', scope: 'server', domain: 'citas' },
    { action: 'recurso_create', scope: 'server', domain: 'citas' },
    { action: 'recurso_list', scope: 'server', domain: 'citas' },
    { action: 'recurso_delete', scope: 'server', domain: 'citas' },
    { action: 'slot_disponibles', scope: 'server', domain: 'citas' },
    { action: 'slot_disponibles_rango', scope: 'server', domain: 'citas' },
    { action: 'cita_publica_crear', scope: 'server', domain: 'citas' },
    // CRM
    { action: 'crm_contacto_create', scope: 'server', domain: 'crm' },
    { action: 'crm_contacto_get', scope: 'server', domain: 'crm' },
    { action: 'crm_contacto_update', scope: 'server', domain: 'crm' },
    { action: 'crm_contacto_delete', scope: 'server', domain: 'crm' },
    { action: 'crm_contacto_list', scope: 'server', domain: 'crm' },
    { action: 'crm_interaccion_add', scope: 'server', domain: 'crm' },
    { action: 'crm_interaccion_list', scope: 'server', domain: 'crm' },
    { action: 'crm_segmento_query', scope: 'server', domain: 'crm' },
    // NOTIFICACIONES
    { action: 'notif_send', scope: 'server', domain: 'notif' },
    { action: 'notif_send_template', scope: 'server', domain: 'notif' },
    { action: 'notif_list', scope: 'server', domain: 'notif' },
    { action: 'notif_template_list', scope: 'server', domain: 'notif' },
    { action: 'notif_template_save', scope: 'server', domain: 'notif' },
    // TAREAS
    { action: 'tarea_create', scope: 'server', domain: 'tareas' },
    { action: 'tarea_list',   scope: 'server', domain: 'tareas' },
    { action: 'tarea_update', scope: 'server', domain: 'tareas' },
    { action: 'tarea_delete', scope: 'server', domain: 'tareas' },
    // DELIVERY
    { action: 'pedido_create', scope: 'server', domain: 'delivery' },
    { action: 'pedido_list', scope: 'server', domain: 'delivery' },
    { action: 'pedido_get', scope: 'server', domain: 'delivery' },
    { action: 'pedido_estado', scope: 'server', domain: 'delivery' },
    { action: 'vehiculo_create', scope: 'server', domain: 'delivery' },
    { action: 'vehiculo_list', scope: 'server', domain: 'delivery' },
    { action: 'vehiculo_update', scope: 'server', domain: 'delivery' },
    { action: 'entrega_asignar', scope: 'server', domain: 'delivery' },
    { action: 'entrega_list_dia', scope: 'server', domain: 'delivery' },
    { action: 'incidencia_add', scope: 'server', domain: 'delivery' },
    { action: 'pedido_seguimiento', scope: 'server', domain: 'delivery' },
    // OPENCLAUDE
    { action: 'openclaude_status',   scope: 'server', domain: 'ai' },
    { action: 'openclaude_complete', scope: 'server', domain: 'ai' },
    // OPENCLAW (agente local bidireccional)
    { action: 'openclaw_manifest',    scope: 'server', domain: 'openclaw' },
    { action: 'openclaw_call',        scope: 'server', domain: 'openclaw' },
    { action: 'openclaw_status',      scope: 'server', domain: 'openclaw' },
    { action: 'openclaw_event_push',  scope: 'server', domain: 'openclaw' },
    // PRECIOS PÚBLICOS — landing page
    { action: 'get_plan_prices', scope: 'server', domain: 'billing' },
    // SUPERADMIN — gestión global SaaS (siempre servidor)
    { action: 'sa_list_locals',          scope: 'server', domain: 'superadmin' },
    { action: 'sa_get_local',            scope: 'server', domain: 'superadmin' },
    { action: 'sa_update_local',         scope: 'server', domain: 'superadmin' },
    { action: 'sa_suspend_local',        scope: 'server', domain: 'superadmin' },
    { action: 'sa_activate_local',       scope: 'server', domain: 'superadmin' },
    { action: 'sa_delete_local',         scope: 'server', domain: 'superadmin' },
    { action: 'sa_override_plan',        scope: 'server', domain: 'superadmin' },
    { action: 'sa_list_plan_defs',       scope: 'server', domain: 'superadmin' },
    { action: 'sa_update_plan_def',      scope: 'server', domain: 'superadmin' },
    { action: 'sa_list_coupons',         scope: 'server', domain: 'superadmin' },
    { action: 'sa_create_coupon',        scope: 'server', domain: 'superadmin' },
    { action: 'sa_update_coupon',        scope: 'server', domain: 'superadmin' },
    { action: 'sa_delete_coupon',        scope: 'server', domain: 'superadmin' },
    { action: 'sa_get_global_config',    scope: 'server', domain: 'superadmin' },
    { action: 'sa_update_global_config', scope: 'server', domain: 'superadmin' },
] as const;

export type ActionName = (typeof ACTION_CATALOG)[number]['action'];

const ACTION_SCOPE_MAP = new Map(ACTION_CATALOG.map((m) => [m.action, m.scope]));

export function getActionScope(action: string): ActionScope {
    return ACTION_SCOPE_MAP.get(action) ?? 'hybrid';
}

export function isLocalOnly(action: string): boolean {
    return getActionScope(action) === 'local';
}

export function requiresServer(action: string): boolean {
    return getActionScope(action) === 'server';
}
